#!/usr/bin/env python
# -*- coding: utf-8 -*-
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from cStringIO import StringIO

cikti = StringIO()
yonetici = PDFResourceManager()
cevirici = TextConverter(yonetici, cikti, laparams=LAParams())
yorumcu = PDFPageInterpreter(yonetici, cevirici)

dosya_yolu = "D:/Dosyalar/deneme.pdf"
dosya = file(dosya_yolu, "rb")

for sayfa in PDFPage.get_pages(dosya):
    yorumcu.process_page(sayfa)

dosya.close()
cevirici.close()

print cikti.getvalue()
cikti.close()
